.nh
.TH "TEAMS" "1" "Oct 2026" "teams dev" "teams Manual"

.SH NAME
teams-version - Print the CLI version and build information


.SH SYNOPSIS
\fBteams version [flags]\fP


.SH DESCRIPTION
Print the CLI version and build information


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	machine-readable JSON output

.PP
\fB--no-color\fP[=false]
	disable colours (also honours NO_COLOR)

.PP
\fB--no-input\fP[=false]
	never prompt; fail fast instead

.PP
\fB--profile\fP=""
	profile to use (default: the configured default_profile)

.PP
\fB--quiet\fP[=false]
	suppress progress messages on stderr

.PP
\fB--read-only\fP[=false]
	refuse write commands

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	verbose diagnostics on stderr (-v, -vv)


.SH SEE ALSO
\fBteams(1)\fP
